site_name: Dhrubajyoti Biswas, PhD
site_url: https://dhrubajyoti98.github.io
copyright: Copyright &copy; 2025 Dhrubajyoti Biswas


nav:
- Home: index.md
- Research: research.md
- Teaching: teaching.md
- Others: misc.md

theme:
  name: material
  font:
    text: Open Sans
  logo: img/favicon.ico
  favicon: img/favicon.ico
  user_color_mode_toggle: light
  nav_style: dark
  features:
    - navigation.instant
    - navigation.instant.progress
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path

  palette:
    primary: black
    accent: red

plugins:
  - social

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      toc_depth: 0

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/djbiswas98
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dhrubajyoti.biswas1/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dhrubajyoti98/
    - icon: fontawesome/solid/paper-plane
      link: mailto:dhrubajyoti98@gmail.com
